FROM node:22-alpine
WORKDIR /app

ENV NODE_ENV=production

RUN apk add --no-cache openssl

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npx prisma generate

CMD ["npx", "ts-node", "--compiler-options", "{\"module\":\"commonjs\"}", "src/workers/pipeline.worker.ts"]
